# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsuarioServiceStub:
    """─── Serviços ─────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarUsuario = channel.unary_unary(
                '/streaming.UsuarioService/CriarUsuario',
                request_serializer=streaming__pb2.CriarUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.Usuario.FromString,
                _registered_method=True)
        self.ObterUsuario = channel.unary_unary(
                '/streaming.UsuarioService/ObterUsuario',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Usuario.FromString,
                _registered_method=True)
        self.ListarUsuarios = channel.unary_unary(
                '/streaming.UsuarioService/ListarUsuarios',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.ListaUsuarios.FromString,
                _registered_method=True)
        self.AtualizarUsuario = channel.unary_unary(
                '/streaming.UsuarioService/AtualizarUsuario',
                request_serializer=streaming__pb2.AtualizarUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.Usuario.FromString,
                _registered_method=True)
        self.RemoverUsuario = channel.unary_unary(
                '/streaming.UsuarioService/RemoverUsuario',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.BoolResponse.FromString,
                _registered_method=True)


class UsuarioServiceServicer:
    """─── Serviços ─────────────────────────────────────────
    """

    def CriarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoverUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarUsuario,
                    request_deserializer=streaming__pb2.CriarUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.Usuario.SerializeToString,
            ),
            'ObterUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterUsuario,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Usuario.SerializeToString,
            ),
            'ListarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarUsuarios,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.ListaUsuarios.SerializeToString,
            ),
            'AtualizarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarUsuario,
                    request_deserializer=streaming__pb2.AtualizarUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.Usuario.SerializeToString,
            ),
            'RemoverUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoverUsuario,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.BoolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.UsuarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.UsuarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsuarioService:
    """─── Serviços ─────────────────────────────────────────
    """

    @staticmethod
    def CriarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.UsuarioService/CriarUsuario',
            streaming__pb2.CriarUsuarioRequest.SerializeToString,
            streaming__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.UsuarioService/ObterUsuario',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.UsuarioService/ListarUsuarios',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.ListaUsuarios.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.UsuarioService/AtualizarUsuario',
            streaming__pb2.AtualizarUsuarioRequest.SerializeToString,
            streaming__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoverUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.UsuarioService/RemoverUsuario',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MusicaServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarMusica = channel.unary_unary(
                '/streaming.MusicaService/CriarMusica',
                request_serializer=streaming__pb2.CriarMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.Musica.FromString,
                _registered_method=True)
        self.ObterMusica = channel.unary_unary(
                '/streaming.MusicaService/ObterMusica',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Musica.FromString,
                _registered_method=True)
        self.ListarMusicas = channel.unary_unary(
                '/streaming.MusicaService/ListarMusicas',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.ListaMusicas.FromString,
                _registered_method=True)
        self.AtualizarMusica = channel.unary_unary(
                '/streaming.MusicaService/AtualizarMusica',
                request_serializer=streaming__pb2.AtualizarMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.Musica.FromString,
                _registered_method=True)
        self.RemoverMusica = channel.unary_unary(
                '/streaming.MusicaService/RemoverMusica',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.BoolResponse.FromString,
                _registered_method=True)


class MusicaServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CriarMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarMusicas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoverMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarMusica,
                    request_deserializer=streaming__pb2.CriarMusicaRequest.FromString,
                    response_serializer=streaming__pb2.Musica.SerializeToString,
            ),
            'ObterMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterMusica,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Musica.SerializeToString,
            ),
            'ListarMusicas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarMusicas,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.ListaMusicas.SerializeToString,
            ),
            'AtualizarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarMusica,
                    request_deserializer=streaming__pb2.AtualizarMusicaRequest.FromString,
                    response_serializer=streaming__pb2.Musica.SerializeToString,
            ),
            'RemoverMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoverMusica,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.BoolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.MusicaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.MusicaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicaService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.MusicaService/CriarMusica',
            streaming__pb2.CriarMusicaRequest.SerializeToString,
            streaming__pb2.Musica.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.MusicaService/ObterMusica',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Musica.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarMusicas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.MusicaService/ListarMusicas',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.ListaMusicas.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.MusicaService/AtualizarMusica',
            streaming__pb2.AtualizarMusicaRequest.SerializeToString,
            streaming__pb2.Musica.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoverMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.MusicaService/RemoverMusica',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PlaylistServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarPlaylist = channel.unary_unary(
                '/streaming.PlaylistService/CriarPlaylist',
                request_serializer=streaming__pb2.CriarPlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.Playlist.FromString,
                _registered_method=True)
        self.ObterPlaylist = channel.unary_unary(
                '/streaming.PlaylistService/ObterPlaylist',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Playlist.FromString,
                _registered_method=True)
        self.ListarPlaylists = channel.unary_unary(
                '/streaming.PlaylistService/ListarPlaylists',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.ListaPlaylists.FromString,
                _registered_method=True)
        self.AtualizarPlaylist = channel.unary_unary(
                '/streaming.PlaylistService/AtualizarPlaylist',
                request_serializer=streaming__pb2.AtualizarPlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.Playlist.FromString,
                _registered_method=True)
        self.RemoverPlaylist = channel.unary_unary(
                '/streaming.PlaylistService/RemoverPlaylist',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.AdicionarMusica = channel.unary_unary(
                '/streaming.PlaylistService/AdicionarMusica',
                request_serializer=streaming__pb2.PlaylistMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.RemoverMusica = channel.unary_unary(
                '/streaming.PlaylistService/RemoverMusica',
                request_serializer=streaming__pb2.PlaylistMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.PlaylistsDoUsuario = channel.unary_unary(
                '/streaming.PlaylistService/PlaylistsDoUsuario',
                request_serializer=streaming__pb2.UsuarioIdRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaPlaylists.FromString,
                _registered_method=True)
        self.MusicasDaPlaylist = channel.unary_unary(
                '/streaming.PlaylistService/MusicasDaPlaylist',
                request_serializer=streaming__pb2.PlaylistIdRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaMusicas.FromString,
                _registered_method=True)
        self.PlaylistsComMusica = channel.unary_unary(
                '/streaming.PlaylistService/PlaylistsComMusica',
                request_serializer=streaming__pb2.MusicaIdRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaPlaylists.FromString,
                _registered_method=True)


class PlaylistServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CriarPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoverPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdicionarMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoverMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaylistsDoUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MusicasDaPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaylistsComMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaylistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarPlaylist,
                    request_deserializer=streaming__pb2.CriarPlaylistRequest.FromString,
                    response_serializer=streaming__pb2.Playlist.SerializeToString,
            ),
            'ObterPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterPlaylist,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.Playlist.SerializeToString,
            ),
            'ListarPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPlaylists,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.ListaPlaylists.SerializeToString,
            ),
            'AtualizarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarPlaylist,
                    request_deserializer=streaming__pb2.AtualizarPlaylistRequest.FromString,
                    response_serializer=streaming__pb2.Playlist.SerializeToString,
            ),
            'RemoverPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoverPlaylist,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.BoolResponse.SerializeToString,
            ),
            'AdicionarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.AdicionarMusica,
                    request_deserializer=streaming__pb2.PlaylistMusicaRequest.FromString,
                    response_serializer=streaming__pb2.BoolResponse.SerializeToString,
            ),
            'RemoverMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoverMusica,
                    request_deserializer=streaming__pb2.PlaylistMusicaRequest.FromString,
                    response_serializer=streaming__pb2.BoolResponse.SerializeToString,
            ),
            'PlaylistsDoUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaylistsDoUsuario,
                    request_deserializer=streaming__pb2.UsuarioIdRequest.FromString,
                    response_serializer=streaming__pb2.ListaPlaylists.SerializeToString,
            ),
            'MusicasDaPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.MusicasDaPlaylist,
                    request_deserializer=streaming__pb2.PlaylistIdRequest.FromString,
                    response_serializer=streaming__pb2.ListaMusicas.SerializeToString,
            ),
            'PlaylistsComMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaylistsComMusica,
                    request_deserializer=streaming__pb2.MusicaIdRequest.FromString,
                    response_serializer=streaming__pb2.ListaPlaylists.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.PlaylistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.PlaylistService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaylistService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.PlaylistService/CriarPlaylist',
            streaming__pb2.CriarPlaylistRequest.SerializeToString,
            streaming__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.PlaylistService/ObterPlaylist',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.PlaylistService/ListarPlaylists',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.ListaPlaylists.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.PlaylistService/AtualizarPlaylist',
            streaming__pb2.AtualizarPlaylistRequest.SerializeToString,
            streaming__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoverPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.PlaylistService/RemoverPlaylist',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdicionarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.PlaylistService/AdicionarMusica',
            streaming__pb2.PlaylistMusicaRequest.SerializeToString,
            streaming__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoverMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.PlaylistService/RemoverMusica',
            streaming__pb2.PlaylistMusicaRequest.SerializeToString,
            streaming__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaylistsDoUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.PlaylistService/PlaylistsDoUsuario',
            streaming__pb2.UsuarioIdRequest.SerializeToString,
            streaming__pb2.ListaPlaylists.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MusicasDaPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.PlaylistService/MusicasDaPlaylist',
            streaming__pb2.PlaylistIdRequest.SerializeToString,
            streaming__pb2.ListaMusicas.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaylistsComMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.PlaylistService/PlaylistsComMusica',
            streaming__pb2.MusicaIdRequest.SerializeToString,
            streaming__pb2.ListaPlaylists.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
