# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: streaming.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto
import grpclib


@dataclass
class Usuario(betterproto.Message):
    """─── Entidades ────────────────────────────────────────"""

    id: int = betterproto.int32_field(1)
    nome: str = betterproto.string_field(2)
    email: str = betterproto.string_field(3)
    criado_em: str = betterproto.string_field(4)


@dataclass
class Musica(betterproto.Message):
    id: int = betterproto.int32_field(1)
    titulo: str = betterproto.string_field(2)
    artista: str = betterproto.string_field(3)
    ano_lancamento: int = betterproto.int32_field(4)
    duracao_segundos: int = betterproto.int32_field(5)
    criado_em: str = betterproto.string_field(6)


@dataclass
class Playlist(betterproto.Message):
    id: int = betterproto.int32_field(1)
    nome: str = betterproto.string_field(2)
    usuario_id: int = betterproto.int32_field(3)
    criado_em: str = betterproto.string_field(4)


@dataclass
class ListaUsuarios(betterproto.Message):
    """─── Listas ───────────────────────────────────────────"""

    usuarios: List["Usuario"] = betterproto.message_field(1)


@dataclass
class ListaMusicas(betterproto.Message):
    musicas: List["Musica"] = betterproto.message_field(1)


@dataclass
class ListaPlaylists(betterproto.Message):
    playlists: List["Playlist"] = betterproto.message_field(1)


@dataclass
class Empty(betterproto.Message):
    """─── Requests genéricos ───────────────────────────────"""

    pass


@dataclass
class IdRequest(betterproto.Message):
    id: int = betterproto.int32_field(1)


@dataclass
class UsuarioIdRequest(betterproto.Message):
    usuario_id: int = betterproto.int32_field(1)


@dataclass
class MusicaIdRequest(betterproto.Message):
    musica_id: int = betterproto.int32_field(1)


@dataclass
class PlaylistIdRequest(betterproto.Message):
    playlist_id: int = betterproto.int32_field(1)


@dataclass
class BoolResponse(betterproto.Message):
    ok: bool = betterproto.bool_field(1)


@dataclass
class CriarUsuarioRequest(betterproto.Message):
    """─── Requests de mutação ──────────────────────────────"""

    nome: str = betterproto.string_field(1)
    email: str = betterproto.string_field(2)


@dataclass
class AtualizarUsuarioRequest(betterproto.Message):
    id: int = betterproto.int32_field(1)
    nome: str = betterproto.string_field(2)
    email: str = betterproto.string_field(3)


@dataclass
class CriarMusicaRequest(betterproto.Message):
    titulo: str = betterproto.string_field(1)
    artista: str = betterproto.string_field(2)
    ano_lancamento: int = betterproto.int32_field(3)
    duracao_segundos: int = betterproto.int32_field(4)


@dataclass
class AtualizarMusicaRequest(betterproto.Message):
    id: int = betterproto.int32_field(1)
    titulo: str = betterproto.string_field(2)
    artista: str = betterproto.string_field(3)
    ano_lancamento: int = betterproto.int32_field(4)
    duracao_segundos: int = betterproto.int32_field(5)


@dataclass
class CriarPlaylistRequest(betterproto.Message):
    nome: str = betterproto.string_field(1)
    usuario_id: int = betterproto.int32_field(2)


@dataclass
class AtualizarPlaylistRequest(betterproto.Message):
    id: int = betterproto.int32_field(1)
    nome: str = betterproto.string_field(2)


@dataclass
class PlaylistMusicaRequest(betterproto.Message):
    playlist_id: int = betterproto.int32_field(1)
    musica_id: int = betterproto.int32_field(2)


class UsuarioServiceStub(betterproto.ServiceStub):
    """─── Serviços ─────────────────────────────────────────"""

    async def criar_usuario(self, *, nome: str = "", email: str = "") -> Usuario:
        request = CriarUsuarioRequest()
        request.nome = nome
        request.email = email

        return await self._unary_unary(
            "/streaming.UsuarioService/CriarUsuario",
            request,
            Usuario,
        )

    async def obter_usuario(self, *, id: int = 0) -> Usuario:
        request = IdRequest()
        request.id = id

        return await self._unary_unary(
            "/streaming.UsuarioService/ObterUsuario",
            request,
            Usuario,
        )

    async def listar_usuarios(self) -> ListaUsuarios:
        request = Empty()

        return await self._unary_unary(
            "/streaming.UsuarioService/ListarUsuarios",
            request,
            ListaUsuarios,
        )

    async def atualizar_usuario(
        self, *, id: int = 0, nome: str = "", email: str = ""
    ) -> Usuario:
        request = AtualizarUsuarioRequest()
        request.id = id
        request.nome = nome
        request.email = email

        return await self._unary_unary(
            "/streaming.UsuarioService/AtualizarUsuario",
            request,
            Usuario,
        )

    async def remover_usuario(self, *, id: int = 0) -> BoolResponse:
        request = IdRequest()
        request.id = id

        return await self._unary_unary(
            "/streaming.UsuarioService/RemoverUsuario",
            request,
            BoolResponse,
        )


class MusicaServiceStub(betterproto.ServiceStub):
    async def criar_musica(
        self,
        *,
        titulo: str = "",
        artista: str = "",
        ano_lancamento: int = 0,
        duracao_segundos: int = 0,
    ) -> Musica:
        request = CriarMusicaRequest()
        request.titulo = titulo
        request.artista = artista
        request.ano_lancamento = ano_lancamento
        request.duracao_segundos = duracao_segundos

        return await self._unary_unary(
            "/streaming.MusicaService/CriarMusica",
            request,
            Musica,
        )

    async def obter_musica(self, *, id: int = 0) -> Musica:
        request = IdRequest()
        request.id = id

        return await self._unary_unary(
            "/streaming.MusicaService/ObterMusica",
            request,
            Musica,
        )

    async def listar_musicas(self) -> ListaMusicas:
        request = Empty()

        return await self._unary_unary(
            "/streaming.MusicaService/ListarMusicas",
            request,
            ListaMusicas,
        )

    async def atualizar_musica(
        self,
        *,
        id: int = 0,
        titulo: str = "",
        artista: str = "",
        ano_lancamento: int = 0,
        duracao_segundos: int = 0,
    ) -> Musica:
        request = AtualizarMusicaRequest()
        request.id = id
        request.titulo = titulo
        request.artista = artista
        request.ano_lancamento = ano_lancamento
        request.duracao_segundos = duracao_segundos

        return await self._unary_unary(
            "/streaming.MusicaService/AtualizarMusica",
            request,
            Musica,
        )

    async def remover_musica(self, *, id: int = 0) -> BoolResponse:
        request = IdRequest()
        request.id = id

        return await self._unary_unary(
            "/streaming.MusicaService/RemoverMusica",
            request,
            BoolResponse,
        )


class PlaylistServiceStub(betterproto.ServiceStub):
    async def criar_playlist(self, *, nome: str = "", usuario_id: int = 0) -> Playlist:
        request = CriarPlaylistRequest()
        request.nome = nome
        request.usuario_id = usuario_id

        return await self._unary_unary(
            "/streaming.PlaylistService/CriarPlaylist",
            request,
            Playlist,
        )

    async def obter_playlist(self, *, id: int = 0) -> Playlist:
        request = IdRequest()
        request.id = id

        return await self._unary_unary(
            "/streaming.PlaylistService/ObterPlaylist",
            request,
            Playlist,
        )

    async def listar_playlists(self) -> ListaPlaylists:
        request = Empty()

        return await self._unary_unary(
            "/streaming.PlaylistService/ListarPlaylists",
            request,
            ListaPlaylists,
        )

    async def atualizar_playlist(self, *, id: int = 0, nome: str = "") -> Playlist:
        request = AtualizarPlaylistRequest()
        request.id = id
        request.nome = nome

        return await self._unary_unary(
            "/streaming.PlaylistService/AtualizarPlaylist",
            request,
            Playlist,
        )

    async def remover_playlist(self, *, id: int = 0) -> BoolResponse:
        request = IdRequest()
        request.id = id

        return await self._unary_unary(
            "/streaming.PlaylistService/RemoverPlaylist",
            request,
            BoolResponse,
        )

    async def adicionar_musica(
        self, *, playlist_id: int = 0, musica_id: int = 0
    ) -> BoolResponse:
        request = PlaylistMusicaRequest()
        request.playlist_id = playlist_id
        request.musica_id = musica_id

        return await self._unary_unary(
            "/streaming.PlaylistService/AdicionarMusica",
            request,
            BoolResponse,
        )

    async def remover_musica(
        self, *, playlist_id: int = 0, musica_id: int = 0
    ) -> BoolResponse:
        request = PlaylistMusicaRequest()
        request.playlist_id = playlist_id
        request.musica_id = musica_id

        return await self._unary_unary(
            "/streaming.PlaylistService/RemoverMusica",
            request,
            BoolResponse,
        )

    async def playlists_do_usuario(self, *, usuario_id: int = 0) -> ListaPlaylists:
        request = UsuarioIdRequest()
        request.usuario_id = usuario_id

        return await self._unary_unary(
            "/streaming.PlaylistService/PlaylistsDoUsuario",
            request,
            ListaPlaylists,
        )

    async def musicas_da_playlist(self, *, playlist_id: int = 0) -> ListaMusicas:
        request = PlaylistIdRequest()
        request.playlist_id = playlist_id

        return await self._unary_unary(
            "/streaming.PlaylistService/MusicasDaPlaylist",
            request,
            ListaMusicas,
        )

    async def playlists_com_musica(self, *, musica_id: int = 0) -> ListaPlaylists:
        request = MusicaIdRequest()
        request.musica_id = musica_id

        return await self._unary_unary(
            "/streaming.PlaylistService/PlaylistsComMusica",
            request,
            ListaPlaylists,
        )
